# Generated by Django 3.2.8 on 2021-12-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korzina', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=True, upload_to=''),
        ),
    ]
