# Generated by Django 3.2.8 on 2021-12-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
