# Generated by Django 3.2.8 on 2021-12-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('product', models.CharField(max_length=200)),
            ],
        ),
    ]
